source "http://rubygems.org"

gem 'builder'
gem 'coderay_bash'
gem 'kramdown'
gem 'mime-types'
gem 'nokogiri', '>= 1.11.0'
gem 'nanoc', '~> 4.0'
gem 'rake'
gem 'yajl-ruby'
gem 'sass'
gem 'bourbon'
gem 'neat'
gem 'fog', '>= 2.0.0'

group :development do
  gem 'listen'
  gem 'rb-fsevent'
  gem 'adsf'
  gem 'fssm'
  gem 'rspec'
end

gem 'pry'
